### ISSUE TITLE
Crash if there are no songs in the library

### ISSUE THREAD

**Issue by DVDAndroid** [karimknaebel/phonograph-issue-tracker#10]
**Requirements:**
- No songs on device

**Steps to reproduce:**
1. Open Phonograph
2. Click on Songs/Albums/Artists tab
3. Click on menu button
4. Click Shuffle all (if there's no crash click twice)
5. Crash

**Logcat:**

```
Process: com.kabouzeid.gramophone, PID: 2856
E/AndroidRuntime( 2856): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
E/AndroidRuntime( 2856):        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
E/AndroidRuntime( 2856):        at java.util.ArrayList.remove(ArrayList.java:403)
E/AndroidRuntime( 2856):        at com.kabouzeid.gramophone.helper.ShuffleHelper.makeShuffleList(Unknown Source)
E/AndroidRuntime( 2856):        at com.kabouzeid.gramophone.service.MusicService.setShuffleMode(Unknown Source)
E/AndroidRuntime( 2856):        at com.kabouzeid.gramophone.helper.MusicPlayerRemote.setShuffleMode(Unknown Source)
E/AndroidRuntime( 2856):        at com.kabouzeid.gramophone.helper.MusicPlayerRemote.openAndShuffleQueue(Unknown Source)
E/AndroidRuntime( 2856):        at com.kabouzeid.gramophone.ui.fragments.mainactivity.library.LibraryFragment.onOptionsItemSelected(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v4.app.Fragment.performOptionsItemSelected(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v4.app.FragmentActivity.onMenuItemSelected(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(Unknown Source)
E/AndroidRuntime( 2856):        at com.kabouzeid.appthemehelper.util.ToolbarContentTintHelper$ATHOnMenuItemClickListener.onMenuItemClick(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v7.widget.Toolbar$1.onMenuItemClick(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v7.view.menu.MenuItemImpl.invoke(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v7.view.menu.MenuBuilder.performItemAction(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v7.view.menu.MenuBuilder.performItemAction(Unknown Source)
E/AndroidRuntime( 2856):        at android.support.v7.view.menu.MenuPopupHelper.onItemClick(Unknown Source)
E/AndroidRuntime( 2856):        at android.widget.AdapterView.performItemClick(AdapterView.java:305)
E/AndroidRuntime( 2856):        at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
E/AndroidRuntime( 2856):        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
E/AndroidRuntime( 2856):        at android.widget.AbsListView$3.run(AbsListView.java:3860)
E/AndroidRuntime( 2856):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 2856):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2856):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2856):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 2856):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2856):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2856):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 2856):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 2856):        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
W/ActivityManager(  772):   Force finishing activity 1 com.kabouzeid.gramophone/.ui.activities.MainActivity
```

**Comment by karimknaebel** [comment]
Thanks for reporting, will fix that :)

**Comment by karimknaebel** [comment]
Fixed internal.
