### ISSUE TITLE
Audio focus denied

### ISSUE THREAD

**Issue by chrisdavis925** [karimknaebel/phonograph-issue-tracker#143]
Hi, 

Love the app! Tried it on a development Android 4.1.2 unit, but whenever a track is selected for play it shows "Audio focus denied" and does not play any track. 

Other apps such as Spotify or the default Music app do not have any issues playing back audio. 

Any thoughts on why this might be?

App version 0.13.1
Android build version   eng.ron.20160826.191053
Android release version 4.2.2
Android SDK version 17
Android build ID    km506_IT
Device brand    Pioneer / NXT
Device manufacturer Pioneer
Device name SABRESD I.MX6
Device model    Pioneer 8100 NEX
ABIs    [armeabi-v7a, armeabi]

**Comment by chrisdavis925** [comment]
In case this helpful, here is verbose logcat:

```
I/OMXPlayer( 2208): Stop Player.
W/FragmentManager( 3540): moveToState: Fragment state for AlbumCoverPagerAdapter$AlbumCoverFragment{416a6258 #2 id=0x7f10010c} not updated inline; exp
ected state 3 found 2
D/GpsChipsManager( 2505): GpsChipsClient::getErrMsg ret=0
D/SxiOperation( 2668): SXI_SOUND  DISCONNECT SXIC_GetSxiModuleInfo
I/ALBUM_ART( 3319):
I/ALBUM_ART( 3319):   openFile is called  uri : content://media/external/audio/media/1235
I/ALBUM_ART( 3319):
I/ALBUM_ART( 3319):   called queryForDataFile
V/MediaProvider( 3319): query = SELECT _data FROM audio WHERE (_id=?)
D/MediaScanner( 3319): convert path: Music/Beyonce/Beyonce - All Night.mp3 to /storage/sdcard0/Music/Beyonce/Beyonce - All Night.mp3
I/ALBUM_ART( 3319):
I/ALBUM_ART( 3319):  [openFileAndEnforcePathPermissionsHelper] album file path : /storage/sdcard0/Music/Beyonce/Beyonce - All Night.mp3
I/OMXPlayer( 2208): file size: 10270385, buffer size : 131072
D/DRM     ( 2208): DivxDrmSetInScanFlag
I/OMXPlayer( 2208): Loading content: sharedfd://19:0:10270385:0
I/OMXPlayer( 2208): LEVEL: 1 FUNCTION: MediaTypeInspect LINE: 1749
I/OMXPlayer( 2208): Can't inspect media content type by subfix.
I/OMXPlayer( 2208): file size: 10270385, buffer size : 131072
I/OMXPlayer( 2208): LEVEL: 1 FUNCTION: ExportIndexTable LINE: 229
I/OMXPlayer( 2208): Fail to open index file to export index: sharedfd://.idx
I/OMXPlayer( 2208): LEVEL: 1 FUNCTION: PreLoad LINE: 655
I/OMXPlayer( 2208): OMX_EventDRMContentUsageeed ret=0
I/OMXPlayer( 2208): LEVEL: 1 FUNCTION: prepare LINE: 416
I/OMXPlayer( 2208): OMXPlayer::prepare
I/OMXPlayer( 2208): LEVEL: 1 FUNCTION: prepare LINE: 473
I/OMXPlayer( 2208): failed to open file: /data/system/audio_pass_through_pref.
I/OMXPlayer( 2208): nPreCacheSize = 31895
V/AudioPolicyManagerMx6( 2208): getOutput() returns output 7
V/AudioPolicyManagerMx6( 2208): getOutput() returns output 7
D/SxiOperation( 2668): SXI_SOUND  DISCONNECT SXIC_GetSxiModuleInfo
W/FragmentManager( 3540): moveToState: Fragment state for AlbumCoverPagerAdapter$AlbumCoverFragment{4141a5a8 #3 id=0x7f10010c} not updated inline; exp
ected state 3 found 2
W/FragmentManager( 3540): moveToState: Fragment state for AlbumCoverPagerAdapter$AlbumCoverFragment{4140f058 #5 id=0x7f10010c} not updated inline; exp
ected state 3 found 2
D/GpsChipsManager( 2505): GpsChipsClient::getErrMsg ret=0
E/AudioManager( 3540): AUDIOMANAGER is android.media.AudioManager@41390550
D/AudioManager( 3540): ===============In The Hash Map========================
D/AudioService( 2816): requestAudioFocus::start requestAudioFocus
D/AudioFocus( 2816): Start JNI request AudioFocus...............................
D/AudioFocus( 2816): clientmap has it ignore it
D/AudioFocus( 2816): start requestAudioFocus
W/AudioFocus( 2504): AudioFocusServer::isCurrentSource 3 android.media.AudioManager@41390550com.kabouzeid.gramophone.service.MusicService$1@41398160 O
FF-SOURCE
D/AudioFocus( 2816): JNI request AudioFocus over
D/AudioFocus( 2816): JNI return ret value
D/AudioService( 2816): requestAudioFocus::Failed requestAudioFocus and out requestAudioFocus
D/SxiOperation( 2668): SXI_SOUND  DISCONNECT SXIC_GetSxiModuleInfo
D/GpsChipsManager( 2505): GpsChipsClient::getErrMsg ret=0
D/SxiOperation( 2668): SXI_SOUND  DISCONNECT SXIC_GetSxiModuleInfo
V/MediaProvider( 3319): query = SELECT _id, name FROM audio_playlists WHERE (name=?) ORDER BY name
D/SxiOperation( 2668): SXI_SOUND  DISCONNECT SXIC_GetSxiModuleInfo
E/org.jaudiotagger.audio( 3540): Unable to find:Music/Beyonce/Beyonce - All Night.mp3
I/wpa_supplicant( 3345): [CTRL_IFACE]wlan0: SIGNAL_POLL
W/System.err( 3540): java.io.FileNotFoundException: Unable to find:Music/Beyonce/Beyonce - All Night.mp3
W/System.err( 3540):    at org.jaudiotagger.audio.AudioFileIO.checkFileExists(Unknown Source)
W/System.err( 3540):    at org.jaudiotagger.audio.AudioFileIO.readFile(Unknown Source)
W/System.err( 3540):    at org.jaudiotagger.audio.AudioFileIO.read(Unknown Source)
W/System.err( 3540):    at com.kabouzeid.gramophone.ui.fragments.player.card.CardPlayerFragment$4.doInBackground(Unknown Source)
W/System.err( 3540):    at com.kabouzeid.gramophone.ui.fragments.player.card.CardPlayerFragment$4.doInBackground(Unknown Source)
W/System.err( 3540):    at android.os.AsyncTask$2.call(AsyncTask.java:287)
W/System.err( 3540):    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
W/System.err( 3540):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
W/System.err( 3540):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
W/System.err( 3540):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
W/System.err( 3540):    at java.lang.Thread.run(Thread.java:856)
```
